### ISSUE TITLE
ACF Sidebar Menu item disappears when activating plugin

### ISSUE THREAD

**Issue by michaellouviere** [colorful-tones/Demo-ACF-Plugin#6]
I have a site I created with Local WP, the only plugins installed are ACF Pro and this DEMO ACF Plugin, as soon as I activate this plugin the ACF menu item in the sidebar disappears. I do have "Site Settings" but no "ACF".

Running ACF Pro Version 6.2.1.1
Demo ACF Plugin Version 0.1.3

**Comment by colorful-tones** [comment]
@michaellouviere this is by design. Here is the feature that does this:

> Added example of restricting access to ACF admin screens based on role && email domain, example: yourAgency.com. So builders can limit admin screens for their clients. See: includes/acf-restrict-access.php

The `demo_acf_show_acf_admin()` function checks for certain email domains and hides the ACF menu if it does not match one of them. Seen here: https://github.com/colorful-tones/Demo-ACF-Plugin/blob/main/includes/acf-restrict-access.php#L34-L35

**Comment by colorful-tones** [comment]
So, you can update those email domains, or just remove the include ([Line #29](https://github.com/colorful-tones/Demo-ACF-Plugin/blob/main/demo-acf-plugin.php#L29)) if you do not desire to have this functionality in your version of the plugin.

**Comment by michaellouviere** [comment]
Interesting, I was following along with [the YouTube video](https://www.youtube.com/watch?v=RIKCtfkgv_k) and at 9:37 when the plugin is activated it doesn't hide the ACF sidebar item. It IS mentioned in passing that this feature exists though but I'm assuming the reason it worked for the demonstrator out of the box is because they have a wpengine.com email address tied to their user which I'm assuming most people using this wouldn't have. 

Adding my email domain to the accept array did fix this. Thank you!!

**Comment by colorful-tones** [comment]
@michaellouviere in the same video at the [29-minute marker](https://youtu.be/RIKCtfkgv_k?si=EH9iw_QP8kMDHyU2&t=1794) is where this is covered.
